server:
  port: 8080

spring:
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/plrecipe
    username: root
    password: mariadb
  web:
    resources:
      static-locations:
        - classpath:/custom-path/
        - classpath:/static/
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: nhJ8WMM3SR5YbRfSWy3l
            client-secret: gEKzM1WS5h
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 1056582183259-a529ncuv59tgqplr5igmujidoo9t06lp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: 21c226427872eec7f4887fa0a4f50465
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

token:
  expiration_time: 43200000000000000
  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==